name: FastAPI CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  deploy:
    needs: test
    if: success()
    runs-on: self-hosted
    steps:
    - name: Deploy Application
      run: |
        cp -r ./* ~/Desktop/News-Harbor-Backend-Deploy/
        cp ~/conf/.env ~/Desktop/News-Harbor-Backend-Deploy/app
        cd ~/Desktop/News-Harbor-Backend-Deploy/app
        docker stop news-harbor-api-container
        docker rm news-harbor-api-container
        docker-compose up -d --build
        