name: React CI

on:
  push:
    paths:
    - Software_Engineering/client/**
    branches: [ main ]
  pull_request:
    paths:
    - Software_Engineering/client/**
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Deploy To PM2
      working-directory: ./Software_Engineering/client
      run: |
        pm2 stop News-Harbor-Client
        cp -r ./news-harbor-client/* ~/Desktop/News-Harbor-Client/
        cd ~/Desktop/News-Harbor-Client/
        npm install
        pm2 start News-Harbor-Client